//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        public int Id_clase { get; set; }
        public string nume_clasa { get; set; }
        public int nr_elevi { get; set; }
    }
}
